export const styles = {
  card: "group relative overflow-hidden cursor-pointer flex flex-col w-full h-full rounded-[2rem] bg-gradient-to-br from-[#fdfbfb] to-[#ebedee] shadow-[0_10px_40px_rgba(0,0,0,0.3)] hover:shadow-[0_20px_60px_rgba(0,0,0,0.5)] transition-all duration-300 hover:-translate-y-2",
  imageWrapper: "relative w-full aspect-[16/9] flex items-center justify-center overflow-hidden rounded-t-[2rem] bg-[#f4f1f8]",
  image: "object-cover w-full h-full transition-transform duration-700 group-hover:scale-105",
  overlay: "absolute inset-0 flex flex-col items-center justify-center gap-4 opacity-0 group-hover:opacity-100 transition-opacity duration-500 p-6 z-10 bg-[#fdfbfb]/95 backdrop-blur-md",
  overlayName: "font-[var(--font-cormorant)] italic text-xl text-center tracking-wide text-[#8a7e94]",
  overlayDivider: "w-8 h-[1px] bg-[#d8cbe3]",
  overlayPrice: "text-xs tracking-widest uppercase text-[#a397ae]",
  overlayActions: "flex flex-col gap-3 w-full max-w-[200px] mt-4",
  overlayBtnDetail: "w-full text-xs tracking-widest uppercase py-3 px-6 rounded text-center transition-colors border border-[#d8cbe3] text-[#8a7e94] hover:bg-[#f4f1f8]",
  overlayBtnWa: "w-full text-xs tracking-widest uppercase py-3 px-6 rounded text-center transition-colors bg-[#e2d5ed] text-[#8a7e94] hover:bg-[#d8cbe3]",
  info: "flex flex-col pt-5 pb-2 flex-grow justify-between px-6",
  infoName: "font-[var(--font-cormorant)] italic text-lg md:text-xl tracking-wide text-[#8a7e94] font-medium",
  infoPrice: "text-sm tracking-wider mt-2 text-[#a397ae]",
};