export const styles = {
  base: {
    card: "group relative overflow-hidden cursor-pointer flex flex-col w-full h-full",
    imageWrapper: "relative w-full aspect-[16/9] flex items-center justify-center overflow-hidden",
    image: "object-cover w-full h-full transition-transform duration-700 group-hover:scale-105",
    imagePlaceholder: "flex flex-col items-center gap-2",
    imagePlaceholderText: "text-[var(--text-faint)] text-xs tracking-widest uppercase",
    overlay: "absolute inset-0 flex flex-col items-center justify-center gap-4 opacity-0 group-hover:opacity-100 transition-opacity duration-500 p-6 z-10",
    overlayName: "font-[var(--font-cormorant)] italic text-xl text-center tracking-wide",
    overlayDivider: "w-8 h-[1px]",
    overlayPrice: "text-xs tracking-widest uppercase",
    overlayActions: "flex flex-col gap-3 w-full max-w-[200px] mt-4",
    overlayBtnDetail: "w-full text-xs tracking-widest uppercase py-3 px-6 rounded text-center transition-colors border",
    overlayBtnWa: "w-full text-xs tracking-widest uppercase py-3 px-6 rounded text-center transition-colors",
    info: "flex flex-col pt-5 pb-2 flex-grow justify-between",
    infoName: "font-[var(--font-cormorant)] italic text-lg md:text-xl tracking-wide",
    infoPrice: "text-sm tracking-wider mt-2",
  },
  magazine: {
    card: "rounded-[2rem] bg-gradient-to-br from-[#fdfbfb] to-[#ebedee] shadow-[0_10px_40px_rgba(0,0,0,0.3)] hover:shadow-[0_20px_60px_rgba(0,0,0,0.5)] transition-all duration-300 hover:-translate-y-2",
    imageWrapper: "rounded-t-[2rem] bg-[#f4f1f8]",
    overlay: "bg-[#fdfbfb]/95 backdrop-blur-md",
    overlayName: "text-[#8a7e94]",
    overlayDivider: "bg-[#d8cbe3]",
    overlayPrice: "text-[#a397ae]",
    overlayBtnDetail: "border-[#d8cbe3] text-[#8a7e94] hover:bg-[#f4f1f8]",
    overlayBtnWa: "bg-[#e2d5ed] text-[#8a7e94] hover:bg-[#d8cbe3]",
    info: "px-6",
    infoName: "text-[#8a7e94] font-medium",
    infoPrice: "text-[#a397ae]",
  },
  pastel: {
    card: "rounded-[2rem] bg-gradient-to-br from-[#fdfbfb] to-[#ebedee] shadow-[0_10px_40px_rgba(0,0,0,0.3)] hover:shadow-[0_20px_60px_rgba(0,0,0,0.5)] transition-all duration-300 hover:-translate-y-2",
    imageWrapper: "rounded-t-[2rem] bg-[#f4f1f8]",
    overlay: "bg-[#fdfbfb]/95 backdrop-blur-md",
    overlayName: "text-[#8a7e94]",
    overlayDivider: "bg-[#d8cbe3]",
    overlayPrice: "text-[#a397ae]",
    overlayBtnDetail: "border-[#d8cbe3] text-[#8a7e94] hover:bg-[#f4f1f8]",
    overlayBtnWa: "bg-[#e2d5ed] text-[#8a7e94] hover:bg-[#d8cbe3]",
    info: "px-6",
    infoName: "text-[#8a7e94] font-medium",
    infoPrice: "text-[#a397ae]",
  }
};